#pragma once

namespace ago {
namespace algorithm {

class GeneTypeAnalyzerHisGram
{
  public:

    GeneTypeAnalyzerHisGram()
    {}

    static void make_file_link( const std::string& p )
    {
        std::string filename;
        std::vector< std::string > list;
        boost::filesystem::path path( p + "../TailDot/" );

        for( auto& file : boost::filesystem::directory_iterator( path ))
        {
            filename = file.path().filename().string();
            if( filename.substr( filename.length() -3  ) == "tsv" )
                list.emplace_back( filename );
        }

        for( auto& file : list )
            if( !boost::filesystem::exists( p + file ))
                 boost::filesystem::create_symlink(( "../TailDot/" + file ).c_str(), ( p + file ).c_str() );
    }

    static void output_hisgram_visualization( const std::string& output_name )
    {
        make_file_link( output_name );
        std::ofstream output( output_name + "index.php" );

        output << "<!DOCTYPE html>" << "\n";
        output << "<html>" << "\n";
        output << "    <meta charset='utf-8'>" << "\n";
        output << "    <body>" << "\n";
        output << "" << "\n";
        output << "    <? " << "\n";
        output << "        Shell_Exec( 'rm /tmp/*' );" << "\n";
        output << "" << "\n";
        output << "        $Type = $_POST['Type'];" << "\n";
        output << "        $isLog = $_POST['isLog'];" << "\n";
        output << "        $is5p3p = $_POST['is5p3p'];" << "\n";
        output << "        $Sample1 = $_POST['Sample1'];" << "\n";
        output << "        $Sample2 = $_POST['Sample2'];" << "\n";
        output << "        $IsomiRs = $_POST['IsomiRs'];" << "\n";
        output << "        $BinCounts = $_POST['BinCounts'];" << "\n";
        output << "        $FilterTop = $_POST['FilterTop'];" << "\n";
        output << "        $FilterDwn = $_POST['FilterDwn'];" << "\n";
        output << "" << "\n";
        output << "        echo '<script src=https://d3js.org/d3.v3.js></script>';" << "\n";
        output << "        echo '<script src=https://cdn.rawgit.com/novus/nvd3/v1.8.6/build/nv.d3.min.js></script>';" << "\n";
        output << "        echo '<link href=https://cdn.rawgit.com/novus/nvd3/v1.8.6/build/nv.d3.css rel=stylesheet type=text/css>';" << "\n";
        output << "" << "\n";
        output << "#<!--=================== GetSamp =====================-->" << "\n";
        output << "        " << "\n";
        output << "        $Samp = Shell_Exec( 'ls *-isomiRs.tsv' );" << "\n";
        output << "        $Samp_List = Explode( \"\\n\", $Samp );" << "\n";
        output << "        $Sample_List = Array();" << "\n";
        output << "" << "\n";
        output << "        For( $i = 0; $i < Count( $Samp_List ); ++$i )" << "\n";
        output << "        {" << "\n";
        output << "            if( $Samp_List[$i] == '' ) continue;" << "\n";
        output << "            $Samp_Name = Explode( '-', $Samp_List[$i] );" << "\n";
        output << "            $Samp_Name = Explode( '/', $Samp_Name[ 0] );" << "\n";
        output << "            Array_Push( $Sample_List, $Samp_Name[ Count( $Samp_Name ) -1 ]);" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "#<!--=================== Sample1 =====================-->" << "\n";
        output << "" << "\n";
        output << "        echo '<form action='.$_SERVER['PHP_SELF'].' method=post style=display:inline;>';" << "\n";
        output << "        echo '<select name=Sample1 onchange=this.form.submit();>';" << "\n";
        output << "        echo '<option '; if($Sample1=='') echo 'selected'; echo '>Select Sample1</option>';" << "\n";
        output << "" << "\n";
        output << "        For( $i = 0; $i < Count( $Sample_List ); ++$i )" << "\n";
        output << "        {" << "\n";
        output << "            if( $Sample_List[$i] == '' ) continue;" << "\n";
        output << "            if( $Sample_List[$i] == $Sample2 ) continue;" << "\n";
        output << "            echo '<option value='.$Sample_List[$i].' ';" << "\n";
        output << "            if( $Sample1 == $Sample_List[$i] ) echo 'selected ';" << "\n";
        output << "            echo '>'.$Sample_List[$i].'</option>';" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "        echo \"</select>" << "\n";
        output << "            <input type='hidden' name='Type' value='$Type' />" << "\n";
        output << "            <input type='hidden' name='isLog' value='$isLog' />" << "\n";
        output << "            <input type='hidden' name='is5p3p' value='$is5p3p' />" << "\n";
        output << "            <input type='hidden' name='Sample2' value='$Sample2' />" << "\n";
        output << "            <input type='hidden' name='IsomiRs' value='$IsomiRs' />" << "\n";
        output << "            <input type='hidden' name='BinCounts' value='$BinCounts' />" << "\n";
        output << "            <input type='hidden' name='FilterTop' value='$FilterTop' />" << "\n";
        output << "            <input type='hidden' name='FilterDwn' value='$FilterDwn' />" << "\n";
        output << "            </form>\";" << "\n";
        output << "" << "\n";
        output << "#<!--=================== Sample2 =====================-->" << "\n";
        output << "" << "\n";
        output << "        echo '<form action='.$_SERVER['PHP_SELF'].' method=post style=display:inline;>';" << "\n";
        output << "        echo '<select name=Sample2 onchange=this.form.submit();>';" << "\n";
        output << "        echo '<option '; if($Sample2=='') echo 'selected'; echo '>Select Sample2</option>';" << "\n";
        output << "" << "\n";
        output << "        For( $i = 0; $i < Count( $Sample_List ); ++$i )" << "\n";
        output << "        {" << "\n";
        output << "            if( $Sample_List[$i] == '' ) continue;" << "\n";
        output << "            if( $Sample_List[$i] == $Sample1 ) continue;" << "\n";
        output << "            echo '<option value='.$Sample_List[$i].' ';" << "\n";
        output << "            if( $Sample2 == $Sample_List[$i] ) echo 'selected ';" << "\n";
        output << "            echo '>'.$Sample_List[$i].'</option>';" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "        echo \"</select>" << "\n";
        output << "            <input type='hidden' name='Type' value='$Type' />" << "\n";
        output << "            <input type='hidden' name='isLog' value='$isLog' />" << "\n";
        output << "            <input type='hidden' name='is5p3p' value='$is5p3p' />" << "\n";
        output << "            <input type='hidden' name='Sample1' value='$Sample1' />" << "\n";
        output << "            <input type='hidden' name='IsomiRs' value='$IsomiRs' />" << "\n";
        output << "            <input type='hidden' name='BinCounts' value='$BinCounts' />" << "\n";
        output << "            <input type='hidden' name='FilterTop' value='$FilterTop' />" << "\n";
        output << "            <input type='hidden' name='FilterDwn' value='$FilterDwn' />" << "\n";
        output << "            </form>\";" << "\n";
        output << "" << "\n";
        output << "#<!--================ 5p3pSelector ==================-->" << "\n";
        output << "" << "\n";
        output << "        echo '<form action='.$_SERVER['PHP_SELF'].' method=post style=display:inline;>';" << "\n";
        output << "        echo '<select name=is5p3p onchange=this.form.submit();>';" << "\n";
        output << "        echo '<option '; if($is5p3p=='') echo 'selected'; echo 'value= >5p3p</option>';" << "\n";
        output << "" << "\n";
        output << "        $Arm_List = array( '5p', '3p' );" << "\n";
        output << "" << "\n";
        output << "        For( $i = 0; $i < Count( $Arm_List ); ++$i )" << "\n";
        output << "        {" << "\n";
        output << "            echo '<option value='.$Arm_List[$i].' ';" << "\n";
        output << "" << "\n";
        output << "            if( $is5p3p == $Arm_List[$i] )" << "\n";
        output << "                echo 'selected ';" << "\n";
        output << "" << "\n";
        output << "            echo '>'.$Arm_List[$i].'</option>';" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "        echo \"</select>" << "\n";
        output << "            <input type='hidden' name='Type' value='$Type' />" << "\n";
        output << "            <input type='hidden' name='isLog' value='$isLog' />" << "\n";
        output << "            <input type='hidden' name='Sample1' value='$Sample1' />" << "\n";
        output << "            <input type='hidden' name='Sample2' value='$Sample2' />" << "\n";
        output << "            <input type='hidden' name='IsomiRs' value='$IsomiRs' />" << "\n";
        output << "            <input type='hidden' name='BinCounts' value='$BinCounts' />" << "\n";
        output << "            <input type='hidden' name='FilterTop' value='$FilterTop' />" << "\n";
        output << "            <input type='hidden' name='FilterDwn' value='$FilterDwn' />" << "\n";
        output << "            </form>\";" << "\n";
        output << "" << "\n";
        output << "#<!--================== IsomiRs =====================-->" << "\n";
        output << "" << "\n";
        output << "        echo '<form action='.$_SERVER['PHP_SELF'].' method=post style=display:inline;>';" << "\n";
        output << "" << "\n";
        output << "        echo '<select name=IsomiRs onchange=this.form.submit();>';" << "\n";
        output << "        echo '<option '; if($IsomiRs=='') echo 'selected'; echo '>Show IsomiRs?</option>';" << "\n";
        output << "" << "\n";
        output << "        $miR_List = array('Yes', 'No');" << "\n";
        output << "" << "\n";
        output << "        For( $i = 0; $i < Count( $miR_List ); ++$i )" << "\n";
        output << "        {" << "\n";
        output << "            echo '<option value='.$miR_List[$i].' ';" << "\n";
        output << "" << "\n";
        output << "            if( $IsomiRs == $miR_List[$i] )" << "\n";
        output << "                echo 'selected ';" << "\n";
        output << "" << "\n";
        output << "            echo '>' . $miR_List[$i] . '</option>';" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "        echo \"</select>" << "\n";
        output << "            <input type='hidden' name='Type' value='$Type' />" << "\n";
        output << "            <input type='hidden' name='isLog' value='$isLog' />" << "\n";
        output << "            <input type='hidden' name='is5p3p' value='$is5p3p' />" << "\n";
        output << "            <input type='hidden' name='Sample1' value='$Sample1' />" << "\n";
        output << "            <input type='hidden' name='Sample2' value='$Sample2' />" << "\n";
        output << "            <input type='hidden' name='BinCounts' value='$BinCounts' />" << "\n";
        output << "            <input type='hidden' name='FilterTop' value='$FilterTop' />" << "\n";
        output << "            <input type='hidden' name='FilterDwn' value='$FilterDwn' />" << "\n";
        output << "            </form>\";" << "\n";
        output << "" << "\n";
        output << "#<!--=============== Type ==================-->" << "\n";
        output << "" << "\n";
        output << "        echo '<form action='.$_SERVER['PHP_SELF'].' method=post style=display:inline;>';" << "\n";
        output << "" << "\n";
        output << "        echo '<select name=Type onchange=this.form.submit();>';" << "\n";
        output << "        echo '<option '; if($Type=='') echo 'selected'; echo '>Select Types</option>';" << "\n";
        output << "" << "\n";
        output << "        $inFileHeader = new SplFileObject( $Sample1.( $IsomiRs == 'Yes' ? '-isomiRs' : '' ).'.tsv' );" << "\n";
        output << "        $inHeaders = Explode( \"\\t\", $inFileHeader->fgets() );" << "\n";
        output << "" << "\n";
        output << "        For( $i = 1; $i < Count( $inHeaders ); ++$i )" << "\n";
        output << "            echo '<option value='.$i.( $Type == $i ? ' selected' : '' ).' >'.$inHeaders[$i].'</option>';" << "\n";
        output << "" << "\n";
        output << "        echo \"</select>" << "\n";
        output << "            <input type='hidden' name='isLog' value='$isLog' />" << "\n";
        output << "            <input type='hidden' name='is5p3p' value='$is5p3p' />" << "\n";
        output << "            <input type='hidden' name='Sample1' value='$Sample1' />" << "\n";
        output << "            <input type='hidden' name='Sample2' value='$Sample2' />" << "\n";
        output << "            <input type='hidden' name='IsomiRs' value='$IsomiRs' />" << "\n";
        output << "            <input type='hidden' name='BinCounts' value='$BinCounts' />" << "\n";
        output << "            <input type='hidden' name='FilterTop' value='$FilterTop' />" << "\n";
        output << "            <input type='hidden' name='FilterDwn' value='$FilterDwn' />" << "\n";
        output << "            </form>\";" << "\n";
        output << "" << "\n";
        output << "#<!--================== isLog ====================-->" << "\n";
        output << "" << "\n";
        output << "        echo '<form action='.$_SERVER['PHP_SELF'].' method=post style=display:inline;>';" << "\n";
        output << "        echo '<select name=isLog onchange=this.form.submit();>';" << "\n";
        output << "        echo '<option '; if($isLog=='') echo 'selected'; echo 'value= >isLog</option>';" << "\n";
        output << "" << "\n";
        output << "        $isLog_List = array(2, 4, 6, 8, 10);" << "\n";
        output << "        $isLog_Size = Count( $isLog_List );" << "\n";
        output << "" << "\n";
        output << "        For( $i = 0; $i < $isLog_Size; ++$i )" << "\n";
        output << "        {" << "\n";
        output << "            echo '<option value='.$isLog_List[$i].' ';" << "\n";
        output << "" << "\n";
        output << "            if( $isLog == $isLog_List[$i] )" << "\n";
        output << "                echo 'selected ';" << "\n";
        output << "" << "\n";
        output << "            echo '>'.$isLog_List[$i].'</option>';" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "        echo \"</select>" << "\n";
        output << "            <input type='hidden' name='Type' value='$Type' />" << "\n";
        output << "            <input type='hidden' name='is5p3p' value='$is5p3p' />" << "\n";
        output << "            <input type='hidden' name='Sample1' value='$Sample1' />" << "\n";
        output << "            <input type='hidden' name='Sample2' value='$Sample2' />" << "\n";
        output << "            <input type='hidden' name='IsomiRs' value='$IsomiRs' />" << "\n";
        output << "            <input type='hidden' name='BinCounts' value='$BinCounts' />" << "\n";
        output << "            <input type='hidden' name='FilterTop' value='$FilterTop' />" << "\n";
        output << "            <input type='hidden' name='FilterDwn' value='$FilterDwn' />" << "\n";
        output << "            </form>\";" << "\n";
        output << "" << "\n";
        output << "#<!--=================== Bin Counts =====================-->" << "\n";
        output << "" << "\n";
        output << "        echo '<form action='.$_SERVER['PHP_SELF'].' method=post style=display:inline;>';" << "\n";
        output << "" << "\n";
        output << "        echo '<input type=text name=BinCounts size=4 value=';" << "\n";
        output << "        echo $BinCounts == '' ? 'BinCounts' : $BinCounts;" << "\n";
        output << "        echo \" onfocus=\\\"{this.value='';}\\\">\";" << "\n";
        output << "" << "\n";
        output << "#<!--================== Bin Filter ====================-->" << "\n";
        output << "" << "\n";
        output << "        echo '<input type=text name=FilterTop size=3 value=';" << "\n";
        output << "        echo $FilterTop == '' ? 'FilterTop' : $FilterTop;" << "\n";
        output << "        echo \" onfocus=\\\"{this.value='';}\\\">\";" << "\n";
        output << "" << "\n";
        output << "        echo '<input type=text name=FilterDwn size=3 value=';" << "\n";
        output << "        echo $FilterDwn == '' ? 'FilterDwn' : $FilterDwn;" << "\n";
        output << "        echo \" onfocus=\\\"{this.value='';}\\\">" << "\n";
        output << "            <input type='hidden' name='Type' value='$Type' />" << "\n";
        output << "            <input type='hidden' name='isLog' value='$isLog' />" << "\n";
        output << "            <input type='hidden' name='is5p3p' value='$is5p3p' />" << "\n";
        output << "            <input type='hidden' name='Sample1' value='$Sample1' />" << "\n";
        output << "            <input type='hidden' name='Sample2' value='$Sample2' />" << "\n";
        output << "            <input type='hidden' name='IsomiRs' value='$IsomiRs' />" << "\n";
        output << "            <input type='submit' value='Submit' />" << "\n";
        output << "            </form>\";" << "\n";
        output << "" << "\n";
        output << "#<!--==================== Switch =====================-->" << "\n";
        output << "" << "\n";
        output << "        echo '<form action='.$_SERVER['PHP_SELF'].' method=post style=display:inline;>';" << "\n";
        output << "        echo \"" << "\n";
        output << "            <input type='submit' value='Switch Samples' /> " << "\n";
        output << "            <input type='hidden' name='Type' value='$Type' />" << "\n";
        output << "            <input type='hidden' name='isLog' value='$isLog' />" << "\n";
        output << "            <input type='hidden' name='is5p3p' value='$is5p3p' />" << "\n";
        output << "            <input type='hidden' name='Sample1' value='$Sample2' />" << "\n";
        output << "            <input type='hidden' name='Sample2' value='$Sample1' />" << "\n";
        output << "            <input type='hidden' name='IsomiRs' value='$IsomiRs' />" << "\n";
        output << "            <input type='hidden' name='BinCounts' value='$BinCounts' />" << "\n";
        output << "            <input type='hidden' name='FilterTop' value='$FilterTop' />" << "\n";
        output << "            <input type='hidden' name='FilterDwn' value='$FilterDwn' />" << "\n";
        output << "            </form><br/>\";" << "\n";
        output << "" << "\n";
        output << "#<!--=================== Read File =====================-->" << "\n";
        output << "" << "\n";
        output << "        $Value_Array = Array();" << "\n";
        output << "        $inFile = new SplFileObject( $Sample1.( $IsomiRs == 'Yes' ? '-isomiRs' : '' ).'.tsv' );" << "\n";
        output << "" << "\n";
        output << "        while( !$inFile->eof() )" << "\n";
        output << "        {" << "\n";
        output << "            $inFile_Lines = $inFile->fgets();" << "\n";
        output << "            if( $inFile_Lines == '' ) continue;" << "\n";
        output << "" << "\n";
        output << "            $inFile_Line = Explode( \"\\t\", $inFile_Lines );" << "\n";
        output << "" << "\n";
        output << "            if( $inFile_Line[0] == $Sample1 ) continue;" << "\n";
        output << "            if( $is5p3p == '5p' && StrPos( $inFile_Line[0], '5p' ) === false ) continue;" << "\n";
        output << "            if( $is5p3p == '3p' && StrPos( $inFile_Line[0], '3p' ) === false ) continue;" << "\n";
        output << "" << "\n";
        output << "            if( $isLog != '' && $inFile_Line[ $Type ] != 0 )" << "\n";
        output << "               $inFile_Line[ $Type ] = Log( $inFile_Line[ $Type ], $isLog );" << "\n";
        output << "" << "\n";
        output << "            if( !array_key_exists( $inFile_Line[0], $Value_Array ))" << "\n";
        output << "            {" << "\n";
        output << "                $Value_Array[ $inFile_Line[0] ] = Array();" << "\n";
        output << "                $Value_Array[ $inFile_Line[0] ][ $Sample1 ] = 0;" << "\n";
        output << "                $Value_Array[ $inFile_Line[0] ][ $Sample2 ] = 0;" << "\n";
        output << "                $Value_Array[ $inFile_Line[0] ][ 'Diff' ] = 0;" << "\n";
        output << "            }" << "\n";
        output << "" << "\n";
        output << "            $Value_Array[ $inFile_Line[0] ][ $Sample1 ] = $inFile_Line[ $Type ];" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "        $inFile = new SplFileObject( $Sample2.( $IsomiRs == 'Yes' ? '-isomiRs' : '' ).'.tsv' );" << "\n";
        output << "" << "\n";
        output << "        while( !$inFile->eof() )" << "\n";
        output << "        {" << "\n";
        output << "            $inFile_Lines = $inFile->fgets();" << "\n";
        output << "            if( $inFile_Lines == '' ) continue;" << "\n";
        output << "" << "\n";
        output << "            $inFile_Line = Explode( \"\\t\", $inFile_Lines );" << "\n";
        output << "" << "\n";
        output << "            if( $inFile_Line[0] == $Sample2 ) continue;" << "\n";
        output << "            if( $is5p3p == '5p' && StrPos( $inFile_Line[0], '5p' ) === false ) continue;" << "\n";
        output << "            if( $is5p3p == '3p' && StrPos( $inFile_Line[0], '3p' ) === false ) continue;" << "\n";
        output << "" << "\n";
        output << "            if( $isLog != '' && $inFile_Line[ $Type ] != 0 )" << "\n";
        output << "               $inFile_Line[ $Type ] = Log( $inFile_Line[ $Type ], $isLog );" << "\n";
        output << "" << "\n";
        output << "            if( !array_key_exists( $inFile_Line[0], $Value_Array ))" << "\n";
        output << "            {" << "\n";
        output << "                $Value_Array[ $inFile_Line[0] ] = Array();" << "\n";
        output << "                $Value_Array[ $inFile_Line[0] ][ $Sample1 ] = 0;" << "\n";
        output << "                $Value_Array[ $inFile_Line[0] ][ $Sample2 ] = 0;" << "\n";
        output << "                $Value_Array[ $inFile_Line[0] ][ 'Diff' ] = 0;" << "\n";
        output << "            }" << "\n";
        output << "" << "\n";
        output << "            $Value_Array[ $inFile_Line[0] ][ $Sample2 ] = $inFile_Line[ $Type ];" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "#<!--=================== DiffValue =====================-->" << "\n";
        output << "        " << "\n";
        output << "        $binMin = 9999999;" << "\n";
        output << "        $binMax = 0;" << "\n";
        output << "" << "\n";
        output << "        foreach( $Value_Array as $Key => $Value )" << "\n";
        output << "        {" << "\n";
        output << "            if( $Value_Array[ $Key ][ $Sample1 ] == 0 && $Value_Array[ $Key ][ $Sample2 ] == 0 )" << "\n";
        output << "            {" << "\n";
        output << "                unset( $Value_Array[ $Key ] );" << "\n";
        output << "                continue;" << "\n";
        output << "            }" << "\n";
        output << "" << "\n";
        output << "            $Value_Array[ $Key ][ 'Diff' ] = $Value_Array[ $Key ][ $Sample1 ] - $Value_Array[ $Key ][ $Sample2 ];" << "\n";
        output << "" << "\n";
        output << "            if( $FilterTop != '' && $FilterTop != 'FilterTop' && Abs( $Value_Array[ $Key ][ 'Diff' ] ) > $FilterTop )" << "\n";
        output << "            {" << "\n";
        output << "                unset( $Value_Array[ $Key ] );" << "\n";
        output << "                continue;" << "\n";
        output << "            }" << "\n";
        output << "" << "\n";
        output << "            if( $FilterDwn != '' && $FilterDwn != 'FilterDwn' && Abs( $Value_Array[ $Key ][ 'Diff' ] ) < $FilterDwn )" << "\n";
        output << "            {" << "\n";
        output << "                unset( $Value_Array[ $Key ] );" << "\n";
        output << "                continue;" << "\n";
        output << "            }" << "\n";
        output << "" << "\n";
        output << "            $Value_Array[ $Key ][ 'Diff' ] = Floor( $Value_Array[ $Key ][ 'Diff' ] * 1000 );" << "\n";
        output << "" << "\n";
        output << "            if( Abs( $Value_Array[ $Key ][ 'Diff' ]) < $binMin ) $binMin = Abs( $Value_Array[ $Key ][ 'Diff' ]);" << "\n";
        output << "            if( Abs( $Value_Array[ $Key ][ 'Diff' ]) > $binMax ) $binMax = Abs( $Value_Array[ $Key ][ 'Diff' ]);" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "        $binMax += 1;" << "\n";
        output << "" << "\n";
        output << "        $binCount = $BinCounts == '' || $BinCounts == 'BinCounts' ? 10 : $BinCounts;" << "\n";
        output << "        $binRange = ( $binMax - $binMin ) / $binCount;" << "\n";
        output << "" << "\n";
        output << "#<!--=================== Make Bin Array =====================-->" << "\n";
        output << "" << "\n";
        output << "        $yMax = 0;" << "\n";
        output << "        $Rcount = $binCount -1;" << "\n";
        output << "        $Ranges = Array();" << "\n";
        output << "" << "\n";
        output << "        $Data_Array = Array();" << "\n";
        output << "        $Data_Array[ $Sample2 ] = Array();" << "\n";
        output << "        $Data_Array[ $Sample1 ] = Array();" << "\n";
        output << "" << "\n";
        output << "        For( $i = $binMax ; $i > $binMin; $i -= $binRange )" << "\n";
        output << "        {" << "\n";
        output << "            if( $Rcount < 0 ) break;" << "\n";
        output << "" << "\n";
        output << "            $Range1 = Number_Format(( $i - $binRange ) / 1000, 3, '.', '' );" << "\n";
        output << "            $Range2 = Number_Format( $i / 1000, 3, '.', '' );" << "\n";
        output << "" << "\n";
        output << "            $Range = $Range1.'~'.$Range2;" << "\n";
        output << "            $Data_Array[ $Sample2 ][ $Range ] = 0;" << "\n";
        output << "            $Data_Array[ $Sample1 ][ $Range ] = 0;" << "\n";
        output << "" << "\n";
        output << "            $Ranges[ $Rcount ] = $Range;" << "\n";
        output << "            $Rcount--;" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "        Foreach( $Value_Array as &$Value )" << "\n";
        output << "        {" << "\n";
        output << "            $Temp = Abs( $Value[ 'Diff' ]);" << "\n";
        output << "" << "\n";
        output << "            if( Intval( $Temp / $binRange ) >= Count( $Ranges )) continue;" << "\n";
        output << "            if( $Value[ 'Diff' ] < 0 ) $Data_Array[ $Sample2 ][ $Ranges[ Intval( $Temp / $binRange )]] -= 1;" << "\n";
        output << "            if( $Value[ 'Diff' ] > 0 ) $Data_Array[ $Sample1 ][ $Ranges[ Intval( $Temp / $binRange )]] += 1;" << "\n";
        output << "" << "\n";
        output << "            if( Abs( $Data_Array[ $Sample2 ][ $Ranges[ Intval( $Temp / $binRange )]]) > $yMax )" << "\n";
        output << "                $yMax = Abs( $Data_Array[ $Sample2 ][ $Ranges[ Intval( $Temp / $binRange )]]);" << "\n";
        output << "" << "\n";
        output << "            if( Abs( $Data_Array[ $Sample1 ][ $Ranges[ Intval( $Temp / $binRange )]]) > $yMax )" << "\n";
        output << "                $yMax = Abs( $Data_Array[ $Sample1 ][ $Ranges[ Intval( $Temp / $binRange )]]);" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "#<!--================== HisGram ====================-->" << "\n";
        output << "" << "\n";
        output << "        echo \"<script>" << "\n";
        output << "            var svg_width  = window.innerWidth;" << "\n";
        output << "            var svg_height = window.innerHeight;" << "\n";
        output << "" << "\n";
        output << "            var margin = {top: 10, right: 20, bottom: 10, left: 20}" << "\n";
        output << "                width  = svg_width  - margin.left - margin.right," << "\n";
        output << "                height = svg_height - margin.top  - margin.bottom;" << "\n";
        output << "" << "\n";
        output << "            var svg = d3.select('body').append('div')" << "\n";
        output << "                .attr('id', 'svg')" << "\n";
        output << "                .style('width', width + 'px')" << "\n";
        output << "                .style('height', height + 'px')" << "\n";
        output << "                .style('display', 'inline-block' )" << "\n";
        output << "                .append('svg');" << "\n";
        output << "" << "\n";
        output << "            nv.addGraph( function() {" << "\n";
        output << "                var chart = nv.models.multiBarHorizontalChart()" << "\n";
        output << "                    .x(function(d) { return d.label })" << "\n";
        output << "                    .y(function(d) { return d.value })" << "\n";
        output << "                    .color([ '#d67777', '#4f99b4' ])" << "\n";
        output << "                    .margin({left: 140})" << "\n";
        output << "                    .groupSpacing(0)" << "\n";
        output << "                    .showControls(true)" << "\n";
        output << "                    .showValues(true)" << "\n";
        output << "                    .stacked(true)" << "\n";
        output << "                    .forceY([-$yMax,0,$yMax])" << "\n";
        output << "                    ;" << "\n";
        output << "" << "\n";
        output << "                d3.select('#svg svg')" << "\n";
        output << "                    .data([data])" << "\n";
        output << "                    .call(chart);" << "\n";
        output << "" << "\n";
        output << "                nv.utils.windowResize(chart.update);" << "\n";
        output << "                return chart;" << "\n";
        output << "            });" << "\n";
        output << "" << "\n";
        output << "            var data = [\";" << "\n";
        output << "" << "\n";
        output << "        Foreach( $Data_Array as $Key => $Data )" << "\n";
        output << "        {" << "\n";
        output << "            echo '{key:\"'.$Key.'\",values:[';" << "\n";
        output << "" << "\n";
        output << "            Foreach( $Data as $Label => $Value )" << "\n";
        output << "            {" << "\n";
        output << "                echo '{label:\"'.$Label.'\",value:'.$Value.'},';" << "\n";
        output << "            }" << "\n";
        output << "" << "\n";
        output << "            echo ']},';" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "        echo '];</script>';" << "\n";
        output << "    ?>" << "\n";
        output << "    </body>" << "\n";
        output << "</html>" << "\n";

        output.close();
    }
};

} // end of namespace algorithm
} // end of namespace ago
