#pragma once
#include <cstdlib>

namespace ago {
namespace algorithm {

class GeneTypeAnalyzerBoxPlot
{

  public:

    GeneTypeAnalyzerBoxPlot()
    {}

    static void make_file_link( const std::string& p )
    {
        std::string filename;
        std::vector< std::string > list;
        boost::filesystem::path path( p + "../TailDot/" );

        for( auto& file : boost::filesystem::directory_iterator( path ))
        {
            filename = file.path().filename().string();
            if( filename.substr( filename.length() -3  ) == "tsv" )
                list.emplace_back( filename );
        }

        for( auto& file : list )
            if( !boost::filesystem::exists( p + file ))
                 boost::filesystem::create_symlink(( "../TailDot/" + file ).c_str(), ( p + file ).c_str() );
    }

    static void output_boxplot_visualization( const std::string& output_name )
    {
        make_file_link( output_name );
        std::ofstream output( output_name + "index.php" );

        output << "<!DOCTYPE html>" << "\n";
        output << "<html>" << "\n";
        output << "    <meta charset='utf-8'>" << "\n";
        output << "    <body>" << "\n";
        output << "" << "\n";
        output << "    <? " << "\n";
        output << "        Shell_Exec( 'rm /tmp/*' );" << "\n";
        output << "" << "\n";
        output << "        $fType = $_POST['fType'];" << "\n";
        output << "        $fValue = $_POST['fValue'];" << "\n";
        output << "        $ForceY = $_POST['ForceY'];" << "\n";
        output << "        $Header = $_POST['Header'];" << "\n";
        output << "        $is5p3p = $_POST['is5p3p'];" << "\n";
        output << "        $isIsomer = $_POST['isIsomer'];" << "\n";
        output << "        $isTrimmed = $_POST['isTrimmed'];" << "\n";
        output << "        $Filter_Pref = $_POST['Filter_Pref'];" << "\n";
        output << "        $Filter_Type = $_POST['Filter_Type'];" << "\n";
        output << "" << "\n";
        output << "        echo '<script src=https://d3js.org/d3.v3.js></script>';" << "\n";
        output << "        echo '<script src=https://cdn.rawgit.com/novus/nvd3/v1.8.6/build/nv.d3.min.js></script>';" << "\n";
        output << "        echo '<link href=https://cdn.rawgit.com/novus/nvd3/v1.8.6/build/nv.d3.css rel=stylesheet type=text/css>';" << "\n";
        output << "" << "\n";
        output << "#<!--================== isIsomer ====================-->" << "\n";
        output << "" << "\n";
        output << "        echo '<form action='.$_SERVER['PHP_SELF'].' method=post style=display:inline;>';" << "\n";
        output << "        echo '<select name=isIsomer onchange=this.form.submit();>';" << "\n";
        output << "        echo '<option '; if($isIsomer=='') echo 'selected'; echo 'value= >isIsomer</option>';" << "\n";
        output << "" << "\n";
        output << "        $Iso_List = array( 'Yes', 'No' );" << "\n";
        output << "" << "\n";
        output << "        For( $i = 0; $i < Count( $Iso_List ); ++$i )" << "\n";
        output << "        {" << "\n";
        output << "            echo '<option value='.$Iso_List[$i].' ';" << "\n";
        output << "" << "\n";
        output << "            if( $isIsomer == $Iso_List[$i] )" << "\n";
        output << "                echo 'selected ';" << "\n";
        output << "" << "\n";
        output << "            echo '>'.$Iso_List[$i].'</option>';" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "        echo \"</select>" << "\n";
        output << "            <input type='hidden' name='fType' value='$fType' />" << "\n";
        output << "            <input type='hidden' name='fValue' value='$fValue' />" << "\n";
        output << "            <input type='hidden' name='ForceY' value='$ForceY' />" << "\n";
        output << "            <input type='hidden' name='Header' value='$Header' />" << "\n";
        output << "            <input type='hidden' name='isTrimmed' value='$isTrimmed' />" << "\n";
        output << "            <input type='hidden' name='Filter_Pref' value='$Filter_Pref' />" << "\n";
        output << "            <input type='hidden' name='Filter_Type' value='$Filter_Type' />" << "\n";
        output << "            </form>\";" << "\n";
        output << "" << "\n";
        output << "#<!--================ 5p3pSelector ==================-->" << "\n";
        output << "" << "\n";
        output << "        echo '<form action='.$_SERVER['PHP_SELF'].' method=post style=display:inline;>';" << "\n";
        output << "        echo '<select name=is5p3p onchange=this.form.submit();>';" << "\n";
        output << "        echo '<option '; if($is5p3p=='') echo 'selected'; echo 'value= >5p3p</option>';" << "\n";
        output << "" << "\n";
        output << "        $Arm_List = array( '5p', '3p' );" << "\n";
        output << "" << "\n";
        output << "        For( $i = 0; $i < Count( $Arm_List ); ++$i )" << "\n";
        output << "        {" << "\n";
        output << "            echo '<option value='.$Arm_List[$i].' ';" << "\n";
        output << "" << "\n";
        output << "            if( $is5p3p == $Arm_List[$i] )" << "\n";
        output << "                echo 'selected ';" << "\n";
        output << "" << "\n";
        output << "            echo '>'.$Arm_List[$i].'</option>';" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "        echo \"</select>" << "\n";
        output << "            <input type='hidden' name='fType' value='$fType' />" << "\n";
        output << "            <input type='hidden' name='fValue' value='$fValue' />" << "\n";
        output << "            <input type='hidden' name='Header' value='$Header' />" << "\n";
        output << "            <input type='hidden' name='ForceY' value='$ForceY' />" << "\n";
        output << "            <input type='hidden' name='isIsomer' value='$isIsomer' />" << "\n";
        output << "            <input type='hidden' name='isTrimmed' value='$isTrimmed' />" << "\n";
        output << "            <input type='hidden' name='Filter_Pref' value='$Filter_Pref' />" << "\n";
        output << "            <input type='hidden' name='Filter_Type' value='$Filter_Type' />" << "\n";
        output << "            </form>\";" << "\n";
        output << "        " << "\n";
        output << "#<!--================== GetHeader ===================-->" << "\n";
        output << "        " << "\n";
        output << "        $TSV_List = Array();" << "\n";
        output << "" << "\n";
        output << "        if( $isIsomer == 'Yes' )" << "\n";
        output << "            $TSV_List = Explode( \"\\n\", Shell_Exec( 'ls | grep isomiRs.tsv' ));" << "\n";
        output << "        " << "\n";
        output << "        if( $isIsomer == 'No' )" << "\n";
        output << "            $TSV_List = Explode( \"\\n\", Shell_Exec( 'ls | grep .tsv | grep -v isomiRs.tsv' ));" << "\n";
        output << "" << "\n";
        output << "        $HeaderIdx = -1;" << "\n";
        output << "        $FilterIdx = 0;" << "\n";
        output << "" << "\n";
        output << "        $Headers = Array();" << "\n";
        output << "        $inFile = new SplFileObject( $TSV_List[0] );" << "\n";
        output << "" << "\n";
        output << "        while( !$inFile->eof() )" << "\n";
        output << "        {" << "\n";
        output << "            $inFile_Lines = $inFile->fgets();" << "\n";
        output << "            if( $inFile_Lines == '' ) continue;" << "\n";
        output << "" << "\n";
        output << "            $inFile_Lines = Str_Replace( '％', '_%', $inFile_Lines );" << "\n";
        output << "            $Headers = Explode( \"\\t\", Rtrim( $inFile_Lines ));" << "\n";
        output << "            $Headers[0] = 'LoadingTrends';" << "\n";
        output << "            break;" << "\n";
        output << "        }" << "\n";
        output << "        " << "\n";
        output << "#<!--================ TypeSelector ==================-->" << "\n";
        output << "" << "\n";
        output << "        echo '<form action='.$_SERVER['PHP_SELF'].' method=post style=display:inline;>';" << "\n";
        output << "        echo '<select name=Header onchange=this.form.submit();>';" << "\n";
        output << "        echo '<option '; if($Header=='') echo 'selected'; echo '>Select Type</option>';" << "\n";
        output << "" << "\n";
        output << "        For( $i = 0; $i < Count( $Headers ); ++$i )" << "\n";
        output << "        {" << "\n";
        output << "            if( $Headers[$i] != '' )" << "\n";
        output << "            {" << "\n";
        output << "                echo '<option value='.$Headers[$i].' ';" << "\n";
        output << "                if( $Header == $Headers[$i] )" << "\n";
        output << "                {" << "\n";
        output << "                    echo 'selected ';" << "\n";
        output << "                    $HeaderIdx = $i;" << "\n";
        output << "                }" << "\n";
        output << "                echo '>'.$Headers[$i].'</option>';" << "\n";
        output << "            }" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "        echo \"</select>" << "\n";
        output << "            <input type='hidden' name='fType' value='$fType' />" << "\n";
        output << "            <input type='hidden' name='fValue' value='$fValue' />" << "\n";
        output << "            <input type='hidden' name='ForceY' value='$ForceY' />" << "\n";
        output << "            <input type='hidden' name='isIsomer' value='$isIsomer' />" << "\n";
        output << "            <input type='hidden' name='isTrimmed' value='$isTrimmed' />" << "\n";
        output << "            <input type='hidden' name='Filter_Pref' value='$Filter_Pref' />" << "\n";
        output << "            <input type='hidden' name='Filter_Type' value='$Filter_Type' />" << "\n";
        output << "            </form>\";" << "\n";
        output << "" << "\n";
        output << "#<!--================= isTrimmed ===================-->" << "\n";
        output << "" << "\n";
        output << "        echo '<form action='.$_SERVER['PHP_SELF'].' method=post style=display:inline;>';" << "\n";
        output << "        echo '<select name=isTrimmed onchange=this.form.submit();>';" << "\n";
        output << "        echo '<option '; if($isTrimmed=='') echo 'selected'; echo 'value= >isTrimmed</option>';" << "\n";
        output << "" << "\n";
        output << "        $Trim_List = array( '1', '5', '10', '20', '25', '30' );" << "\n";
        output << "        $Trim_Size = Count( $Trim_List );" << "\n";
        output << "" << "\n";
        output << "        For( $i = 0; $i < $Trim_Size; ++$i )" << "\n";
        output << "        {" << "\n";
        output << "            echo '<option value='.$Trim_List[$i].' ';" << "\n";
        output << "" << "\n";
        output << "            if( $isTrimmed == $Trim_List[$i] )" << "\n";
        output << "                echo 'selected ';" << "\n";
        output << "" << "\n";
        output << "            echo '>±'.$Trim_List[$i].'％</option>';" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "        echo '</select>';" << "\n";
        output << "" << "\n";
        output << "#<!--================== ForceY ====================-->" << "\n";
        output << "" << "\n";
        output << "        echo '<input type=text name=ForceY size=3 value=';" << "\n";
        output << "" << "\n";
        output << "        if( $ForceY=='' )" << "\n";
        output << "            echo 'Hight';" << "\n";
        output << "        else" << "\n";
        output << "            echo $ForceY;" << "\n";
        output << "" << "\n";
        output << "        echo \" onfocus=\\\"{this.value='';}\\\"></select>\";" << "\n";
        output << "" << "\n";
        output << "        if( $ForceY == 'Hight' ) $ForceY = '';" << "\n";
        output << "" << "\n";
        output << "#<!--=============== ContentFilter ================-->" << "\n";
        output << "        " << "\n";
        output << "        echo '<select name=fType onchange=this.form.submit();>';" << "\n";
        output << "        echo '<option '; if($fType=='') echo 'selected'; echo '>Filter Type</option>';" << "\n";
        output << "" << "\n";
        output << "        For( $i = 1; $i < Count( $Headers ); ++$i )" << "\n";
        output << "        {" << "\n";
        output << "            if( $Headers[$i] != '' )" << "\n";
        output << "            {" << "\n";
        output << "                echo '<option value='.$Headers[$i].' ';" << "\n";
        output << "                if( $fType == $Headers[$i] )" << "\n";
        output << "                {" << "\n";
        output << "                    echo 'selected ';" << "\n";
        output << "                    $FilterIdx = $i;" << "\n";
        output << "                }" << "\n";
        output << "                echo '>'.$Headers[$i].'</option>';" << "\n";
        output << "            }" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "        echo '</select>';" << "\n";
        output << "" << "\n";
        output << "#<!--================ FilterValue =================-->" << "\n";
        output << "" << "\n";
        output << "        if( $fType == '' || $fType == 'Filter Type' ) $fValue = '';" << "\n";
        output << "" << "\n";
        output << "        echo '<input type=text name=fValue size=3 value=';" << "\n";
        output << "" << "\n";
        output << "        if( $fValue=='' )" << "\n";
        output << "            echo '<=';" << "\n";
        output << "        else" << "\n";
        output << "            echo $fValue;" << "\n";
        output << "" << "\n";
        output << "        echo \" onfocus=\\\"{this.value='';}\\\"></select>\";" << "\n";
        output << "" << "\n";
        output << "#<!--================== Filter ====================-->" << "\n";
        output << "" << "\n";
        output << "        $Pref_List = array( 'UniLike', 'DisLike' );" << "\n";
        output << "        $Type_List = array( 'GMPM', 'GM', 'PM', 'Atail', 'Ctail', 'Gtail', 'Utail' );" << "\n";
        output << "" << "\n";
        output << "        echo '<select name=Filter_Pref>';" << "\n";
        output << "        echo '<option value=\"\"'; if($Filter_Pref=='') echo 'selected'; echo '>Preference Filter</option>';" << "\n";
        output << "" << "\n";
        output << "        For( $i = 0; $i < Count( $Pref_List ); ++$i )" << "\n";
        output << "        {" << "\n";
        output << "            echo '<option value='.$Pref_List[$i].' ';" << "\n";
        output << "            if( $Filter_Pref == $Pref_List[$i] ) echo 'selected ';" << "\n";
        output << "            echo '>'.$Pref_List[$i].'</option>';" << "\n";
        output << "        }" << "\n";
        output << "        echo '</select>';" << "\n";
        output << "" << "\n";
        output << "        echo '<select name=Filter_Type>';" << "\n";
        output << "        echo '<option value=\"\"'; if($Filter_Type=='') echo 'selected'; echo '>Preference Type</option>';" << "\n";
        output << "" << "\n";
        output << "        For( $i = 0; $i < Count( $Type_List ); ++$i )" << "\n";
        output << "        {" << "\n";
        output << "            echo '<option value='.$Type_List[$i].' ';" << "\n";
        output << "            if( $Filter_Type == $Type_List[$i] ) echo 'selected ';" << "\n";
        output << "            echo '>'.$Type_List[$i].'</option>';" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "        echo \"</select>" << "\n";
        output << "            <input type='hidden' name='Header' value='$Header' />" << "\n";
        output << "            <input type='hidden' name='isIsomer' value='$isIsomer' />" << "\n";
        output << "            <input type='hidden' name='isTrimmed' value='$isTrimmed' />" << "\n";
        output << "            <input type='submit' value='Submit' /> " << "\n";
        output << "            </form><br/>\";" << "\n";
        output << "" << "\n";
        output << "#<!--================== Read Filter ====================-->" << "\n";
        output << "" << "\n";
        output << "        $Filter_Anno = Array();" << "\n";
        output << "" << "\n";
        output << "        if( $Filter_Type != '' && $Filter_Type != 'Preference Type' &&" << "\n";
        output << "            $Filter_Pref != '' && $Filter_Pref != 'Preference Filter' )" << "\n";
        output << "        {" << "\n";
        output << "            For( $i = 0; $i < Count( $TSV_List ); ++$i )" << "\n";
        output << "            {" << "\n";
        output << "                if( $TSV_List[$i] == '' ) continue;" << "\n";
        output << "                $Sample = Explode( '/', $TSV_List[$i] );" << "\n";
        output << "                $Sample = Explode( '.', $Sample[ Count( $Sample ) -1 ] );" << "\n";
        output << "                $Sample = Explode( '-', $Sample[0] )[0];" << "\n";
        output << "" << "\n";
        output << "                $Filter_TSV = '../Preference/'.$Filter_Type.'/'.$Sample.'_'.$Filter_Pref;" << "\n";
        output << "                $Filter_TSV = $Filter_TSV.( $isIsomer == 'No' ? '' : '-isomiRs' ).'.text';" << "\n";
        output << "" << "\n";
        output << "                $inFile = new SplFileObject( $Filter_TSV );" << "\n";
        output << "                $Filter_Anno[ $i ] = Array();" << "\n";
        output << "" << "\n";
        output << "                while( !$inFile->eof() )" << "\n";
        output << "                {" << "\n";
        output << "                    $inFile_Lines = Rtrim( $inFile->fgets() );" << "\n";
        output << "                    if( $inFile_Lines == '' ) continue;" << "\n";
        output << "" << "\n";
        output << "                    $inFile_Lines = Explode( '*', $inFile_Lines )[0];" << "\n";
        output << "                    $inFile_Lines = Explode( '!', $inFile_Lines )[0];" << "\n";
        output << "                    $inFile_Lines = Explode( '|', $inFile_Lines )[0];" << "\n";
        output << "" << "\n";
        output << "                    Array_Push( $Filter_Anno[ $i ], $inFile_Lines );" << "\n";
        output << "                }" << "\n";
        output << "            }" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "#<!--=================== Read File =====================-->" << "\n";
        output << "" << "\n";
        output << "        $yMax = 0;" << "\n";
        output << "" << "\n";
        output << "        $TSVs_Array = Array();" << "\n";
        output << "        $Hete_Array = Array();" << "\n";
        output << "        $Boxs_Array = Array();" << "\n";
        output << "" << "\n";
        output << "        $Anno_Array = Array();" << "\n";
        output << "        $Tand_Array = Array();" << "\n";
        output << "" << "\n";
        output << "        For( $i = 0; $i < Count( $TSV_List ); ++$i )" << "\n";
        output << "        {" << "\n";
        output << "            $isHeader = true;" << "\n";
        output << "            if( $TSV_List[$i] == '' ) continue;" << "\n";
        output << "            $inFile = new SplFileObject( $TSV_List[$i] );" << "\n";
        output << "" << "\n";
        output << "            while( !$inFile->eof() )" << "\n";
        output << "            {" << "\n";
        output << "                $inFile_Lines = $inFile->fgets();" << "\n";
        output << "                if( $inFile_Lines == '' ) continue;" << "\n";
        output << "" << "\n";
        output << "                $inFile_Lines = Explode( \"\\t\", Rtrim( $inFile_Lines ));" << "\n";
        output << "" << "\n";
        output << "                if( $isHeader )" << "\n";
        output << "                {" << "\n";
        output << "                    $isHeader = false;" << "\n";
        output << "                    $TSVs_Array[ $i ] = Substr( $TSV_List[$i], 0, Strlen( $TSV_List[$i] ) -4 );" << "\n";
        output << "                    $Hete_Array[ $i ] = Array();" << "\n";
        output << "                    $Boxs_Array[ $i ] = Array();" << "\n";
        output << "                    $Tand_Array[ $i ] = Array();" << "\n";
        output << "                    continue;" << "\n";
        output << "                }" << "\n";
        output << "" << "\n";
        output << "                if( In_Array( $inFile_Lines[0], $Filter_Anno[ $i ] ) === false ) continue;" << "\n";
        output << "                if( $is5p3p == '5p' && StrPos( $inFile_Lines[0], '5p' ) === false ) continue;" << "\n";
        output << "                if( $is5p3p == '5p' && StrPos( $inFile_Lines[0], '5p' ) === false ) continue;" << "\n";
        output << "" << "\n";
        output << "                if( $FilterIdx == 4 && $inFile_Lines[ $FilterIdx ] == 1 ) continue;" << "\n";
        output << "                if( $FilterIdx != 0 && $inFile_Lines[ $FilterIdx ] == 0 ) continue;" << "\n";
        output << "                if( $FilterIdx != 0 && $inFile_Lines[ $FilterIdx ] < $fValue ) continue;" << "\n";
        output << "" << "\n";
        output << "                if( $HeaderIdx == 0 )" << "\n";
        output << "                {" << "\n";
        output << "                    $inFile_Lines[0] = Explode( '*', $inFile_Lines[0] )[0];" << "\n";
        output << "                    $inFile_Lines[0] = Explode( '!', $inFile_Lines[0] )[0];" << "\n";
        output << "                    $inFile_Lines[0] = Explode( '|', $inFile_Lines[0] )[0];" << "\n";
        output << "" << "\n";
        output << "                    if( Array_Key_Exists( $inFile_Lines[0], $Tand_Array[ $i ] ))" << "\n";
        output << "                         $Tand_Array[ $i ][ $inFile_Lines[0] ] += $inFile_Lines[1];" << "\n";
        output << "                    else $Tand_Array[ $i ][ $inFile_Lines[0] ] =  $inFile_Lines[1];" << "\n";
        output << "" << "\n";
        output << "                    Array_Push( $Anno_Array, $inFile_Lines[0] );" << "\n";
        output << "                    continue;" << "\n";
        output << "                }" << "\n";
        output << "" << "\n";
        output << "                if( $inFile_Lines[ $HeaderIdx ] == 0 ) continue;" << "\n";
        output << "                if( $HeaderIdx == 4 && $inFile_Lines[ $HeaderIdx ] == 1 ) continue;" << "\n";
        output << "" << "\n";
        output << "                Array_Push( $Hete_Array[ $i ], $inFile_Lines[ $HeaderIdx ] );" << "\n";
        output << "            }" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "        if( $HeaderIdx == 0 )" << "\n";
        output << "        {" << "\n";
        output << "            Sort( $Anno_Array, SORT_STRING );" << "\n";
        output << "            $Anno_Array = Array_Unique( $Anno_Array, SORT_STRING );" << "\n";
        output << "            $Anno_Array = Array_Values( $Anno_Array );" << "\n";
        output << "" << "\n";
        output << "            For( $i = 0; $i < Count( $Anno_Array ); ++$i )" << "\n";
        output << "            {" << "\n";
        output << "                $Sum = 0;" << "\n";
        output << "" << "\n";
        output << "                For( $j = 0; $j < Count( $Tand_Array ); ++$j )" << "\n";
        output << "                    $Sum += $Tand_Array[$j][ $Anno_Array[$i] ];" << "\n";
        output << "" << "\n";
        output << "                if( $Sum == 0 ) continue;" << "\n";
        output << "" << "\n";
        output << "                For( $j = 0; $j < Count( $Tand_Array ); ++$j )" << "\n";
        output << "                {" << "\n";
        output << "                    if( $Tand_Array[$j][ $Anno_Array[$i] ] == 0 ) continue;" << "\n";
        output << "                    Array_Push( $Hete_Array[ $j ], $Tand_Array[$j][ $Anno_Array[$i] ] / $Sum );" << "\n";
        output << "                }" << "\n";
        output << "            }" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "        For( $i = 0; $i < Count( $Hete_Array ); ++$i )" << "\n";
        output << "        {" << "\n";
        output << "            Sort( $Hete_Array[$i] );" << "\n";
        output << "" << "\n";
        output << "            $Boxs_Array[$i][ 'Q1' ] = $Hete_Array[$i][ Floor(( Count( $Hete_Array[$i] ) -1 ) * 0.25 )];" << "\n";
        output << "            $Boxs_Array[$i][ 'Q2' ] = $Hete_Array[$i][ Floor(( Count( $Hete_Array[$i] ) -1 ) * 0.5  )];" << "\n";
        output << "            $Boxs_Array[$i][ 'Q3' ] = $Hete_Array[$i][ Floor(( Count( $Hete_Array[$i] ) -1 ) * 0.75 )];" << "\n";
        output << "            $Boxs_Array[$i][ 'whisker_low'  ] = $Hete_Array[$i][0];" << "\n";
        output << "            $Boxs_Array[$i][ 'whisker_high' ] = $Hete_Array[$i][ Count( $Hete_Array[$i] ) -1];" << "\n";
        output << "" << "\n";
        output << "            if( $isTrimmed != '' )" << "\n";
        output << "            {" << "\n";
        output << "                $Rate = $isTrimmed / 100;" << "\n";
        output << "                $Boxs_Array[$i][ 'whisker_low'  ] = $Hete_Array[$i][ Floor(( Count( $Hete_Array[$i] ) -1 ) *       $Rate  )];" << "\n";
        output << "                $Boxs_Array[$i][ 'whisker_high' ] = $Hete_Array[$i][ Floor(( Count( $Hete_Array[$i] ) -1 ) * ( 1 - $Rate ))];" << "\n";
        output << "            }" << "\n";
        output << "" << "\n";
        output << "            if( $Boxs_Array[$i][ 'whisker_high' ] > $yMax ) $yMax = $Boxs_Array[$i][ 'whisker_high' ];" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "        if( $ForceY != '' ) $yMax = $ForceY;" << "\n";
        output << "" << "\n";
        output << "#<!--================== BoxPlot ====================-->" << "\n";
        output << "" << "\n";
        output << "        echo \"<script>" << "\n";
        output << "            var svg_width  = window.innerWidth;" << "\n";
        output << "            var svg_height = window.innerHeight;" << "\n";
        output << "" << "\n";
        output << "            var margin = {top: 10, right: 20, bottom: 10, left: 20}" << "\n";
        output << "                width  = svg_width  - margin.left - margin.right," << "\n";
        output << "                height = svg_height - margin.top  - margin.bottom;" << "\n";
        output << "" << "\n";
        output << "            var svg = d3.select('body').append('div')" << "\n";
        output << "                .attr('id', 'svg')" << "\n";
        output << "                .style('width', width + 'px')" << "\n";
        output << "                .style('height', height + 'px')" << "\n";
        output << "                .style('display', 'inline-block' )" << "\n";
        output << "                .append('svg');" << "\n";
        output << "" << "\n";
        output << "            nv.addGraph( function() {" << "\n";
        output << "                var chart = nv.models.boxPlotChart()" << "\n";
        output << "                    .x(function(d) { return d.label })" << "\n";
        output << "                    .staggerLabels(true)" << "\n";
        output << "                    .maxBoxWidth(75) // prevent boxes from being incredibly wide" << "\n";
        output << "                    .yDomain([\".( $HeaderIdx == 4 ? '1' : '0' ).\", $yMax]);" << "\n";
        output << "" << "\n";
        output << "                d3.select('#svg svg')" << "\n";
        output << "                    .data([data])" << "\n";
        output << "                    .call(chart);" << "\n";
        output << "" << "\n";
        output << "                nv.utils.windowResize(chart.update);" << "\n";
        output << "                return chart;" << "\n";
        output << "            });" << "\n";
        output << "" << "\n";
        output << "            var data = [\";" << "\n";
        output << "" << "\n";
        output << "        For( $i = 0; $i < Count( $Boxs_Array ); ++$i )" << "\n";
        output << "        {" << "\n";
        output << "            echo '{label:\"'.$TSVs_Array[$i].'\",values:{';" << "\n";
        output << "" << "\n";
        output << "            Foreach( $Boxs_Array[$i] as $Q => $Value )" << "\n";
        output << "                echo $Q.':'.$Value.',';" << "\n";
        output << "" << "\n";
        output << "            echo 'outliers:[]}}';" << "\n";
        output << "            if( $i != Count( $Boxs_Array )-1 ) echo \",\\n\";" << "\n";
        output << "        }" << "\n";
        output << "" << "\n";
        output << "        echo '];</script>';" << "\n";
        output << "    ?>" << "\n";
        output << "    </body>" << "\n";
        output << "</html>" << "\n";

        output.close();
    }
};

} // end of namespace algorithm
} // end of namespace ago
